### ISSUE TITLE
This module is not making reference to the obvious pun

### ISSUE THREAD

**Issue by TheAlphaNerd** [davglass/cpr#10]
![just saying](https://pbs.twimg.com/media/B9BtcmKIYAAU0KE.jpg:large)

**Comment by jesstelford** [comment]
+1

Please don't let this idea die.

**Comment by silverwind** [comment]
:weary:

**Comment by davglass** [comment]
I added the image to the readme, I just need to come up with a funny tagline for it too.

**Comment by silverwind** [comment]
"Massaging your files the right way"

I'd opt for a better image, this is literally the first google image result.

**Comment by yaymukund** [comment]
:laughing:
