### ISSUE TITLE
overwrite:true removes dirs if they exist

### ISSUE THREAD

**Issue by dschmidt** [davglass/cpr#18]
Hey,

`cpr` removes dirs if they already exist, if `overwrite:true` is specified in options (which I assumed was just the same as `-f`).

So for a `test.js` which contains this: 
```javascript
var cpr = require('cpr');

cpr('build/', 'deployments/', {
    deleteFirst: false,
    overwrite: true,
    confirm: false
}, function(err, files) {
    if(err) {
        console.error('ERROR', err);
        return;
    }

    console.log('SUCCESS');
});

```

I see this behavior:

```bash
% find build             
build
build/assets
build/assets/2

% find deployments
deployments
deployments/assets
deployments/assets/1

% node test.js
SUCCESS

% find deployments/         
deployments/
deployments/assets
deployments/assets/2
```

whereas `cp -R -f` does the following:

```
% find build 
build
build/assets
build/assets/2

% find deployments 
deployments
deployments/assets
deployments/assets/1

% cp -R build/* deployments 
% find deployments
deployments
deployments/assets
deployments/assets/1
deployments/assets/2
```

and without `overwrite: true` it fails on the already existing `assets/` dir (and possibly other already existing files). So right now there seems to be no way to merge to directory trees with `cpr`. ... or am I overlooking anything?

AFAICT this is the code causing this behavior: https://github.com/davglass/cpr/blob/master/lib/index.js#L113

Why was that code added in the first place?

BR,
Domme

**Comment by davglass** [comment]
Sorry, I've been away with some family issues. I'll have a patch that you can test shortly.

**Comment by dschmidt** [comment]
Don't worry, I'm glad you agree it's a bug :+1: 

I just wasn't sure it wasn't desired behavior, or how you wanted it to be fixed, thus I did not send a PR directly. If you fix, even better :-)

**Comment by davglass** [comment]
I have a fix locally, I'm just writing the tests for it now. I'll push it to master without publishing so you can test it to confirm that it behaves as you wanted.

**Comment by davglass** [comment]
GH closed it as I pushed up the fix. Can you try master and see if that works as you expect it to? If it does then I'll publish this as `1.0.0`.

**Comment by dschmidt** [comment]
Nice! Will test when back from dinner

**Comment by dschmidt** [comment]
Works, great!

**Comment by davglass** [comment]
Cool, published as `cpr@1.0.0`.

**Comment by dschmidt** [comment]
Yay, so is ember-cli-deploy-cp@0.3.0 ;-)

Thanks for taking care of this so quickly :beer:

**Comment by jeffbonhag** [comment]
:+1: Thanks for the fix

**Comment by davglass** [comment]
Always glad to help! :beers:
