### ISSUE TITLE
Please add a CLI

### ISSUE THREAD

**Issue by BigstickCarpet** [davglass/cpr#19]
It would be great if cpr included a CLI.  This would make it super easy to write scripts that work across Linux, Mac, and Windows.  Something like this:

```
cpr [source_dir] [destination_dir]
```

And if you want to be _really_ awesome, you could support multiple source files and/or globs:

```
cpr [source_file1] [source_file2] [...source_fileN] [destination_dir]

cpr [source_glob] [destination_dir]
```

**Comment by davglass** [comment]
I don't plan on adding this support as it's not what I intended this module to me. It would not be hard for someone to write a cli wrapper around this module. I'll leave it here in case someone wants to tackle it but I won't be doing it any time soon.

**Comment by gvn** [comment]
+1
