### ISSUE TITLE
CLI options?

### ISSUE THREAD

**Issue by screendriver** [davglass/cpr#26]
It is possible to pass the API [options](https://github.com/davglass/cpr#options) as arguments to the CLI interface? E.g. `cpr --overwrite foo bar`

**Comment by davglass** [comment]
We didn't add many options as I didn't want to add the weight of an options parser to every install of `cpr`. I'm not opposed to it, I just don't want the added dependency on every install.

**Comment by screendriver** [comment]
You could add [yargs](https://www.npmjs.com/package/yargs). But if you don't want add dependencies it's ok for me. Then I have to look for another Node CLI tool for directory copies. Maybe I write one by myself.

Thank you for the quick response.

**Comment by davglass** [comment]
No reason to write a new one, you can just wrap `cpr` in a custom CLI. It has all the options and it works ;)

**Comment by screendriver** [comment]
Hmm that's true :smile:

**Comment by stevenvachon** [comment]
I think that it's still necessary for npm scripts. I'd like to overwrite when I copy. I don't understand the concern with dependencies when `mkdirp` already uses `minimist`.

**Comment by screendriver** [comment]
I created a copy CLI tool by [myself](https://github.com/screendriver/cp-cli) for that :wink:

**Comment by stevenvachon** [comment]
@screendriver that has no overwrite option. Nothing against your library, but having to write your own separate library to accomplish something that a more mature, actively developed library can do is redundant.

**Comment by screendriver** [comment]
Yes it's a little redundant. But what should I do? I needed a cross platform CLI tool that copies and override everything (and follows symbolic links) for our continuous integration system in my company. Unfortunately your CLI can't do that and you don't want to add an option for that. So the only solution was to build my own micro tool that does that job.

**Comment by stevenvachon** [comment]
@screendriver the other option is to convince this library's author to implement its options in the cli.

**Comment by stevenvachon** [comment]
@davglass why not implement access to the options? As mentioned above, `mkdirp` already depends on `minimist`, so we could easily do the same.

**Comment by davglass** [comment]
@stevenvachon I originally didn't add a CLI option, it was contributed as a PR a few months ago. I wouldn't object to a full CLI to come in another PR ;)

**Comment by davglass** [comment]
@screendriver I just published v2.0.0 with the PR from @stevenvachon that adds CLI options.
