### ISSUE TITLE
Does not behave like cp -R when copying a single file

### ISSUE THREAD

**Issue by ldanet** [davglass/cpr#28]
Hi, 

I had assumed that this module would behave like the command it takes its name from, but it appears it does not do so when copying single files.

Say you have this file structure:
```
foo/
 `-- bar.jpg
baz/
```
and you want to copy `foo/bar.jpg` to `baz/qux.jpg`.

When you execute `cp -R foo/bar.jpg baz/qux.jpg` in command line, it creates a renamed copy to the target path. You get:
```
foo/
 `-- bar.jpg
baz/
 `-- qux.jpg
```
When using this project, on the other hand, you get:
```
foo/
 `-- bar.jpg
baz/
 `-- qux.jpg/
      `-- bar.jpg
```
I was relying on this behavior to have a generic purpose file copy module.

**Comment by davglass** [comment]
Yeah, this module copies full directories and not just single files. I'll look into this when I get a chance.
