### ISSUE TITLE
Missing change log

### ISSUE THREAD

**Issue by Turbo87** [davglass/cpr#31]
I am unable to find a change log for this project anywhere. It would be good to know what changed between all those releases and the major ones with potentially breaking changes in particular.

**Comment by davglass** [comment]
My apologies for not adding one, but I've never really needed to keep one. Every release only contains one or two minor fixes and each of them are well documented in the commit logs: 
https://github.com/davglass/cpr/commits/master

**Comment by Turbo87** [comment]
@davglass I guess if you could add tags to the release commits you could use something like https://github.com/skywinder/github-changelog-generator to generate the change log automatically for you

**Comment by davglass** [comment]
I had all the tags locally just never pushed them, just added a Changelog script that will now generate one: https://github.com/davglass/cpr/blob/master/CHANGELOG.md
